# Stage 1: Build stage
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json to leverage caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Stage 2: Development stage
FROM node:18-alpine AS development

# Set the working directory
WORKDIR /app

# Copy only the package files and node_modules from the build stage
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

# Copy the rest of the application code
COPY . .

# Expose the port for the Next.js application
EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]